"""
orchestrator.py
================
Ties together the API clients, prompt construction, and validation to run
the full multi-turn interaction:

    Turn 1 (A): initial position on the topic
    Turn 2 (B): critique / question / expansion on A's response
    Turn 3 (A): final reply addressing B's critique
    Turn 4 (synthesis): short neutral conclusion, generated by a final
                        orchestration call to Model A

Each turn is validated for schema conformance and topic relevance; if a
turn fails either check, a corrective re-prompt is sent back to the same
model (up to `max_correction_attempts` extra tries) before the whole run
is reported as failed. All prompts and raw model outputs are logged.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from config import OrchestrationConfig
from llm_client import LLMAPIError, LLMClient
from prompts import (
    TURN_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
    build_initial_prompt,
    build_critique_prompt,
    build_rebuttal_prompt,
    build_synthesis_prompt,
    build_correction_prompt,
)
from validation import (
    LLMResponseValidationError,
    parse_llm_json,
    validate_turn_schema,
    validate_synthesis_schema,
    validate_relevance,
)

logger = logging.getLogger("multi_model_debate")


@dataclass
class DebateResult:
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    failed_at_turn: Optional[str] = None


def setup_logging(log_file: str, verbose: bool = False) -> None:
    """Configures the shared logger to write to both console and a log file.

    File gets DEBUG level (full prompts + raw outputs); console gets INFO
    (high-level flow) unless verbose=True.
    """
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()

    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG if verbose else logging.INFO)
    console_handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)


class MultiModelOrchestrator:
    def __init__(
        self,
        client_a: LLMClient,
        client_b: LLMClient,
        orchestration_config: Optional[OrchestrationConfig] = None,
    ):
        self.client_a = client_a
        self.client_b = client_b
        self.config = orchestration_config or OrchestrationConfig()

    # -----------------------------------------------------------------
    # Generic single-turn runner: call model -> parse -> validate ->
    # correct-and-retry if needed. Shared by every discussion turn.
    # -----------------------------------------------------------------
    def _run_turn(
        self,
        client: LLMClient,
        system_prompt: str,
        initial_user_prompt: str,
        topic: str,
        turn_label: str,
        schema_validator,
        check_relevance: bool,
    ) -> Dict[str, Any]:
        messages: List[Dict[str, str]] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": initial_user_prompt},
        ]

        total_attempts = self.config.max_correction_attempts + 1
        last_raw = ""

        for attempt in range(1, total_attempts + 1):
            logger.info("[%s] Attempt %d/%d: sending prompt to %s", turn_label, attempt, total_attempts, client.config.label)

            try:
                raw = client.call(messages)
            except LLMAPIError as exc:
                logger.error("[%s] API call failed: %s", turn_label, exc)
                raise

            last_raw = raw
            problems: List[str] = []

            try:
                parsed = parse_llm_json(raw)
            except LLMResponseValidationError as exc:
                problems = [str(exc)]
                parsed = None

            if parsed is not None:
                problems = schema_validator(parsed)

                if not problems and check_relevance:
                    is_relevant, ratio = validate_relevance(
                        topic, parsed.get("response", ""), self.config.min_relevance_overlap
                    )
                    logger.debug("[%s] Relevance overlap ratio: %.3f (threshold %.3f)", turn_label, ratio, self.config.min_relevance_overlap)
                    if not is_relevant:
                        problems = [
                            f"Response does not appear to engage with the topic "
                            f"(lexical overlap ratio {ratio:.2f} below threshold "
                            f"{self.config.min_relevance_overlap:.2f}). Address the topic directly."
                        ]

            if not problems:
                logger.info("[%s] Validated successfully on attempt %d", turn_label, attempt)
                return parsed

            logger.warning("[%s] Attempt %d failed validation: %s", turn_label, attempt, problems)

            if attempt < total_attempts:
                messages.append({"role": "assistant", "content": raw})
                messages.append({"role": "user", "content": build_correction_prompt(raw, "; ".join(problems))})
                continue

            raise LLMResponseValidationError(
                f"[{turn_label}] {client.config.label} failed validation after {attempt} attempt(s): "
                + "; ".join(problems)
            )

        raise LLMResponseValidationError(f"[{turn_label}] Unreachable validation failure.")

    # -----------------------------------------------------------------
    # Full debate orchestration
    # -----------------------------------------------------------------
    def run_debate(self, topic: str) -> DebateResult:
        if not topic or not topic.strip():
            return DebateResult(success=False, error="Topic is empty.")

        logger.info("=== Starting multi-model debate on topic: %r ===", topic)

        try:
            # Turn 1: Model A initial position
            turn1 = self._run_turn(
                client=self.client_a,
                system_prompt=TURN_SYSTEM_PROMPT,
                initial_user_prompt=build_initial_prompt(topic),
                topic=topic,
                turn_label="Turn 1 (Model A initial)",
                schema_validator=validate_turn_schema,
                check_relevance=True,
            )

            # Turn 2: Model B critique
            turn2 = self._run_turn(
                client=self.client_b,
                system_prompt=TURN_SYSTEM_PROMPT,
                initial_user_prompt=build_critique_prompt(topic, turn1["response"]),
                topic=topic,
                turn_label="Turn 2 (Model B critique)",
                schema_validator=validate_turn_schema,
                check_relevance=True,
            )

            # Turn 3: Model A final reply
            turn3 = self._run_turn(
                client=self.client_a,
                system_prompt=TURN_SYSTEM_PROMPT,
                initial_user_prompt=build_rebuttal_prompt(topic, turn1["response"], turn2["response"]),
                topic=topic,
                turn_label="Turn 3 (Model A rebuttal)",
                schema_validator=validate_turn_schema,
                check_relevance=True,
            )

            # Turn 4: synthesis (orchestration call to Model A; relevance
            # check skipped since the conclusion legitimately references
            # both models' positions rather than restating the topic verbatim)
            synthesis = self._run_turn(
                client=self.client_a,
                system_prompt=SYNTHESIS_SYSTEM_PROMPT,
                initial_user_prompt=build_synthesis_prompt(topic, turn1["response"], turn2["response"], turn3["response"]),
                topic=topic,
                turn_label="Turn 4 (Synthesis)",
                schema_validator=validate_synthesis_schema,
                check_relevance=False,
            )

        except LLMAPIError as exc:
            logger.error("Debate aborted due to API failure: %s", exc)
            return DebateResult(success=False, error=f"API error: {exc}")
        except LLMResponseValidationError as exc:
            logger.error("Debate aborted due to validation failure: %s", exc)
            return DebateResult(success=False, error=f"Validation error: {exc}")

        final_output = {
            "topic": topic,
            "model_a_initial_response": turn1,
            "model_b_critique": turn2,
            "model_a_final_reply": turn3,
            "conclusion": synthesis["conclusion"],
        }

        logger.info("=== Debate completed successfully ===")
        return DebateResult(success=True, data=final_output)
