"""
orchestrator.py
================
Ties together the API clients, prompt construction, and validation to run
the full adversarial reasoning cycle:

    Turn 1 (A): initial proposal/position with reasoning
    Turn 2 (B): adversarial critique -- weaknesses, risks, edge cases
    Turn 3 (A): revision or defense addressing the critique
    Turn 4 (evaluation): final robustness/remaining-risks summary,
                         generated by a final orchestration call to Model A

Each turn is validated for schema conformance and topic relevance; if a
turn fails either check, a corrective re-prompt is sent back to the same
model (up to `max_correction_attempts` extra tries) before the whole run
is reported as failed. All prompts and raw model outputs are logged.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

from config import OrchestrationConfig
from llm_client import LLMAPIError, LLMClient
from prompts import (
    PROPOSAL_SYSTEM_PROMPT,
    CRITIQUE_SYSTEM_PROMPT,
    REVISION_SYSTEM_PROMPT,
    FINAL_EVALUATION_SYSTEM_PROMPT,
    build_proposal_prompt,
    build_critique_prompt,
    build_revision_prompt,
    build_final_evaluation_prompt,
    build_correction_prompt,
)
from validation import (
    LLMResponseValidationError,
    parse_llm_json,
    validate_proposal_schema,
    validate_critique_schema,
    validate_revision_schema,
    validate_final_evaluation_schema,
    validate_relevance,
)

logger = logging.getLogger("adversarial_reasoning")


@dataclass
class ReasoningResult:
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


def setup_logging(log_file: str, verbose: bool = False) -> None:
    """Configures the shared logger: DEBUG (full prompts + raw outputs) to
    the log file, INFO (high-level flow) to the console unless verbose."""
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()

    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG if verbose else logging.INFO)
    console_handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)


class AdversarialReasoningOrchestrator:
    def __init__(
        self,
        client_a: LLMClient,
        client_b: LLMClient,
        orchestration_config: Optional[OrchestrationConfig] = None,
    ):
        self.client_a = client_a
        self.client_b = client_b
        self.config = orchestration_config or OrchestrationConfig()

    # -----------------------------------------------------------------
    # Generic single-turn runner: call model -> parse -> validate ->
    # correct-and-retry if needed. Shared by every turn in the cycle.
    # -----------------------------------------------------------------
    def _run_turn(
        self,
        client: LLMClient,
        system_prompt: str,
        initial_user_prompt: str,
        user_input: str,
        turn_label: str,
        schema_validator: Callable[[Any], List[str]],
        relevance_text_field: Optional[str],
    ) -> Dict[str, Any]:
        messages: List[Dict[str, str]] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": initial_user_prompt},
        ]

        total_attempts = self.config.max_correction_attempts + 1

        for attempt in range(1, total_attempts + 1):
            logger.info("[%s] Attempt %d/%d: sending prompt to %s", turn_label, attempt, total_attempts, client.config.label)

            try:
                raw = client.call(messages)
            except LLMAPIError as exc:
                logger.error("[%s] API call failed: %s", turn_label, exc)
                raise

            problems: List[str] = []
            parsed = None

            try:
                parsed = parse_llm_json(raw)
            except LLMResponseValidationError as exc:
                problems = [str(exc)]

            if parsed is not None:
                problems = schema_validator(parsed)

                if not problems and relevance_text_field is not None:
                    is_relevant, ratio = validate_relevance(
                        user_input, parsed.get(relevance_text_field, ""), self.config.min_relevance_overlap
                    )
                    logger.debug(
                        "[%s] Relevance overlap ratio: %.3f (threshold %.3f)",
                        turn_label, ratio, self.config.min_relevance_overlap,
                    )
                    if not is_relevant:
                        problems = [
                            f"Response does not appear to engage with the original scenario "
                            f"(lexical overlap ratio {ratio:.2f} below threshold "
                            f"{self.config.min_relevance_overlap:.2f}). Address the scenario directly."
                        ]

            if not problems:
                logger.info("[%s] Validated successfully on attempt %d", turn_label, attempt)
                return parsed

            logger.warning("[%s] Attempt %d failed validation: %s", turn_label, attempt, problems)

            if attempt < total_attempts:
                messages.append({"role": "assistant", "content": raw})
                messages.append({"role": "user", "content": build_correction_prompt(raw, "; ".join(problems))})
                continue

            raise LLMResponseValidationError(
                f"[{turn_label}] {client.config.label} failed validation after {attempt} attempt(s): "
                + "; ".join(problems)
            )

        raise LLMResponseValidationError(f"[{turn_label}] Unreachable validation failure.")

    # -----------------------------------------------------------------
    # Full adversarial reasoning cycle
    # -----------------------------------------------------------------
    def run(self, user_input: str) -> ReasoningResult:
        if not user_input or not user_input.strip():
            return ReasoningResult(success=False, error="Input scenario is empty.")

        logger.info("=== Starting adversarial reasoning on input: %r ===", user_input)

        try:
            # Turn 1: Model A initial proposal
            turn1 = self._run_turn(
                client=self.client_a,
                system_prompt=PROPOSAL_SYSTEM_PROMPT,
                initial_user_prompt=build_proposal_prompt(user_input),
                user_input=user_input,
                turn_label="Turn 1 (Model A proposal)",
                schema_validator=validate_proposal_schema,
                relevance_text_field="proposal",
            )

            # Turn 2: Model B critique
            turn2 = self._run_turn(
                client=self.client_b,
                system_prompt=CRITIQUE_SYSTEM_PROMPT,
                initial_user_prompt=build_critique_prompt(user_input, turn1["proposal"]),
                user_input=user_input,
                turn_label="Turn 2 (Model B critique)",
                schema_validator=validate_critique_schema,
                relevance_text_field="critique",
            )

            # Turn 3: Model A revision/defense
            turn3 = self._run_turn(
                client=self.client_a,
                system_prompt=REVISION_SYSTEM_PROMPT,
                initial_user_prompt=build_revision_prompt(user_input, turn1["proposal"], turn2["critique"]),
                user_input=user_input,
                turn_label="Turn 3 (Model A revision)",
                schema_validator=validate_revision_schema,
                relevance_text_field="revised_response",
            )

            # Turn 4: final evaluation (orchestration call to Model A;
            # relevance check skipped since a robustness summary
            # legitimately references the critique/revision rather than
            # restating the scenario verbatim)
            evaluation = self._run_turn(
                client=self.client_a,
                system_prompt=FINAL_EVALUATION_SYSTEM_PROMPT,
                initial_user_prompt=build_final_evaluation_prompt(
                    user_input, turn1["proposal"], turn2["critique"], turn3["revised_response"]
                ),
                user_input=user_input,
                turn_label="Turn 4 (Final evaluation)",
                schema_validator=validate_final_evaluation_schema,
                relevance_text_field=None,
            )

        except LLMAPIError as exc:
            logger.error("Reasoning cycle aborted due to API failure: %s", exc)
            return ReasoningResult(success=False, error=f"API error: {exc}")
        except LLMResponseValidationError as exc:
            logger.error("Reasoning cycle aborted due to validation failure: %s", exc)
            return ReasoningResult(success=False, error=f"Validation error: {exc}")

        final_output = {
            "original_input": user_input,
            "model_a_initial_proposal": turn1,
            "model_b_critique": turn2,
            "model_a_revised_response": turn3,
            "final_evaluation": evaluation,
        }

        logger.info("=== Adversarial reasoning cycle completed successfully ===")
        return ReasoningResult(success=True, data=final_output)
